plugins {
    id 'net.fabricmc.fabric-loom' version "${loom_version}"
    id 'com.gradleup.shadow' version '8.3.5'
    id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

repositories {
    mavenCentral()
    flatDir { dirs 'libs' }
    maven { url 'https://jitpack.io' }
}

loom {
    splitEnvironmentSourceSets()
    mods {
        "sky-bubble" {
            sourceSet sourceSets.main
            sourceSet sourceSets.client
        }
    }
}

configurations {
    shade
    implementation.extendsFrom shade
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

    shade 'com.github.Eleeterrr:ElFontLib:main-SNAPSHOT'
    shade "com.google.code.gson:gson:2.11.0"
}

tasks.jar {
    enabled = false
}

shadowJar {
    configurations = [project.configurations.shade]
    from sourceSets.main.output
    from sourceSets.client.output
    archiveClassifier.set('')
}

tasks.build {
    dependsOn shadowJar
}

tasks.assemble {
    dependsOn shadowJar
}

processResources {
    def version = project.version
    inputs.property "version", version
    filesMatching("fabric.mod.json") {
        expand "version": version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 25
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}